### ISSUE TITLE
请问如何使用呢

### ISSUE THREAD

**Issue by xiaosadexiaohai** [ghjacky/DingTalkAlertGateway#1]
请问如何使用呢

**Comment by ghjacky** [comment]
python manage.py runserver 0.0.0.0:8000
里边的字段信息需要根据实际情况自己去修改相应的东西

**Comment by kenkong2019** [comment]
请教一下，open_dnsdb那个问题具体怎么操作？

(.venv) [root@minion02 open_dnsdb]# tools/with_venv.sh python setup.py install
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/util.py", line 270, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/open_dnsdb/.venv/lib/python3.6/site-packages/pbr/packaging.py", line 874, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name dnsdb was given, but was not able to be found.
error in setup command: Error parsing /usr/local/open_dnsdb/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name dnsdb was given, but was not able to be found.
